project_name: Test
tasks:
  - name: Data Stream double value 1
    type: processor_nats
    code: double.go
    targets:
      - cloud
    source_topic: test_source_data
    dest_topic: ttest_dest_data
    component_name: data_double_test1
    version: 1.0.0

  - name: Data Stream double value 2
    type: processor_nats
    code: double.go
    targets:
      - cloud
    source_topic: test_source_data
    dest_topic: ttest_dest_data
    component_name: data_double_test2
    version: 1.0.0

  - name: Data Stream double value 3
    type: processor_nats
    code: double.go
    targets:
      - cloud
    source_topic: test_source_data
    dest_topic: ttest_dest_data
    component_name: data_double_test3
    version: 1.0.0

  - name: Data Stream double value 4
    type: processor_nats
    code: double.go
    targets:
      - cloud
    source_topic: test_source_data
    dest_topic: ttest_dest_data
    component_name: data_double_test4
    version: 1.0.0

  - name: Data Stream double value 5
    type: processor_nats
    code: double.go
    targets:
      - cloud
    source_topic: test_source_data
    dest_topic: ttest_dest_data
    component_name: data_double_test5
    version: 1.0.0

  - name: Data Stream double value 6
    type: processor_nats
    code: double.go
    targets:
      - cloud
    source_topic: test_source_data
    dest_topic: ttest_dest_data
    component_name: data_double_test6
    version: 1.0.0

  - name: Data Stream double value 7
    type: processor_nats
    code: double.go
    targets:
      - cloud
    source_topic: test_source_data
    dest_topic: ttest_dest_data
    component_name: data_double_test7
    version: 1.0.0

  - name: Data Stream double value 8
    type: processor_nats
    code: double.go
    targets:
      - cloud
    source_topic: test_source_data
    dest_topic: ttest_dest_data
    component_name: data_double_test8
    version: 1.0.0

  - name: Data Stream double value 9
    type: processor_nats
    code: double.go
    targets:
      - cloud
    source_topic: test_source_data
    dest_topic: ttest_dest_data
    component_name: data_double_test9
    version: 1.0.0

  - name: Data Stream double value 10
    type: processor_nats
    code: double.go
    targets:
      - cloud
    source_topic: test_source_data
    dest_topic: ttest_dest_data
    component_name: data_double_test10
    version: 1.0.0
