project_name: Test
tasks:
  - name: Data Aggregation
    type: processor_nats
    code: task1.go
    targets:
      - edge
      - cloud
    source_topic: temp_sensor
    dest_topic: aggregated_data
    component_name: data_aggregation
    version: 1.0.0
  - name: Aiutatemi
    type: processor_nats
    code: danano.go
    targets:
      - edge
    source_topic: test
    dest_topic: temp_sensor
    component_name: test_producer
    version: 1.0.0