project_name: Test
tasks:
  - name: Data Stream test 1
    type: processor_nats
    code: task1.go
    targets:
      - cloud
    source_topic: test_source
    dest_topic: test_destination
    component_name: data_aggregation_test
    version: 1.0.0
  - name: Aiutatemi
    type: producer_nats
    code: danano.go
    targets:
      - edge
    source_topic: test
    dest_topic: test_source
    component_name: test_producer_help1
    version: 1.0.0
  - name: Aiutatemi
    type: producer_nats
    code: danano.go
    targets:
      - edge
    source_topic: test
    dest_topic: test_source
    component_name: test_producer_help2
    version: 1.0.0
  - name: Aiutatemi
    type: producer_nats
    code: danano.go
    targets:
      - edge
    source_topic: test
    dest_topic: test_source
    component_name: test_producer_help3
    version: 1.0.0
  - name: Aiutatemi
    type: producer_nats
    code: danano.go
    targets:
      - edge
    source_topic: test
    dest_topic: test_source
    component_name: test_producer_help4
    version: 1.0.0