project_name: Test
tasks:
  - name: Data Aggregation
    type: producer_nats
    code: task1.go
    targets:
      - edge
      - cloud
    source_topic: temp_sensor
    dest_topic: aggregated_data
    component_name: data_aggregation
    version: 1.0.0
  - name: Daniele pelato
    type: processor_nats
    code: danano.go
    targets:
      - edge
    source_topic: temp_sensor
    dest_topic: sexo
    component_name: liscio
    version: 1.0.0